# Generated by Django 4.1 on 2022-08-28 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notice_alter_course_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phone',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('BT', 'Btech'), ('MBT', 'MBATech'), ('MT', 'Mtech')], default='Btech', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='qualifications',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
